/* DiaMerna — Full Build Script
   Usage: node build-all.js [--desktop] [--mobile] [--release]

   Steps:
   1. Encrypt API keys from environment variables
   2. Inject encrypted keys into desktop + mobile builds
   3. (optional) Build desktop EXE
   4. (optional) Build mobile APK
   5. Prepare release assets */

const { execSync } = require('child_process')
const path = require('path')
const fs = require('fs')

const ROOT = path.join(__dirname, '..')
const VER = '1.0.0'

function run(cmd, cwd) {
  console.log(`\n> ${cmd}`)
  try { execSync(cmd, { cwd: cwd || ROOT, stdio: 'inherit', shell: true }) }
  catch(e) { console.error('Build step failed:', e.message); process.exit(1) }
}

function banner(t) { console.log('\n' + '='.repeat(60) + '\n  ' + t + '\n' + '='.repeat(60)) }

/* === Step 1: Encrypt API keys === */
banner('Encrypting API keys')
run('node encrypt-keys.js')
const encryptedFile = path.join(ROOT, 'desktop', 'encrypted-keys.json')
if (!fs.existsSync(encryptedFile)) { console.error('Encryption failed — encrypted-keys.json not found'); process.exit(1) }
const encrypted = JSON.parse(fs.readFileSync(encryptedFile, 'utf8'))
const hasKeys = Object.values(encrypted.secrets).some(v => v && v.length > 0)
console.log(hasKeys ? '✅ Real API keys found and encrypted' : '⚠️ No real keys — using placeholders')

/* === Step 2: Inject into mobile config === */
banner('Injecting encrypted keys into mobile config')
const mobileConfigPath = path.join(ROOT, 'mobile', 'encrypted-config.js')
const configJs = `
// DiaMerna — Encrypted runtime config for mobile
// Auto-generated by build-all.js — DO NOT EDIT
window.ENCRYPTED_CONFIG = ${JSON.stringify(encrypted, null, 2)};
`
fs.writeFileSync(mobileConfigPath, configJs)
console.log('✅ Mobile encrypted config written')

/* === Step 3: Generate icon === */
banner('Generating app icon')
run('node scripts/gen-icon.js')

/* === Step 4: Build Electron desktop (EXE) === */
if (process.argv.includes('--desktop')) {
  banner('Building Electron desktop app (EXE)')
  run('npm install', path.join(ROOT, 'desktop'))
  run('npx electron-builder --win', path.join(ROOT, 'desktop'))
  console.log('✅ Desktop EXE built in desktop/dist/')
}

/* === Step 5: Build Android APK === */
if (process.argv.includes('--mobile')) {
  banner('Building Android APK')
  run('npm install', path.join(ROOT, 'mobile'))
  run('npx cap sync', path.join(ROOT, 'mobile'))
  run('npm run build:apk', path.join(ROOT, 'mobile'))
  console.log('✅ APK built in mobile/android/app/build/outputs/apk/release/')
}

/* === Step 6: Collect release assets === */
banner('Collecting release assets')
const releaseDir = path.join(ROOT, 'dist-release')
if (fs.existsSync(releaseDir)) fs.rmSync(releaseDir, { recursive: true })
fs.mkdirSync(releaseDir, { recursive: true })

/* Source code (no secrets) */
const srcZip = path.join(releaseDir, `diamerna-source-v${VER}.zip`)
run(`powershell Compress-Archive -Path "${ROOT}\\dev", "${ROOT}\\api", "${ROOT}\\desktop\\package.json", "${ROOT}\\mobile\\package.json", "${ROOT}\\mobile\\capacitor.config.json", "${ROOT}\\encrypt-keys.js", "${ROOT}\\scripts", "${ROOT}\\package.json", "${ROOT}\\vercel.json", "${ROOT}\\README.md" -DestinationPath "${srcZip}" -Force`)

/* Desktop EXE */
const exeDir = path.join(ROOT, 'desktop', 'dist')
if (fs.existsSync(exeDir)) {
  fs.readdirSync(exeDir).filter(f => f.endsWith('.exe')).forEach(f => {
    fs.copyFileSync(path.join(exeDir, f), path.join(releaseDir, f))
    console.log(`✅ Copied ${f}`)
  })
}

/* Mobile APK */
const apkPath = path.join(ROOT, 'mobile', 'android', 'app', 'build', 'outputs', 'apk', 'release')
if (fs.existsSync(apkPath)) {
  fs.readdirSync(apkPath).filter(f => f.endsWith('.apk')).forEach(f => {
    fs.copyFileSync(path.join(apkPath, f), path.join(releaseDir, f))
    console.log(`✅ Copied ${f}`)
  })
}

console.log('\n✅ All release assets in dist-release/')
console.log(`  - Source: diamerna-source-v${VER}.zip`)
console.log(`  - Desktop EXE: DiaMerna-Setup-${VER}.exe (if built)`)
console.log(`  - Mobile APK: DiaMerna-${VER}.apk (if built)`)
